provider:
  name: i3dnet
resources:
  flexmetal_server:
    create:
      path: /v3/flexMetal/servers
      method: POST
    read:
      path: /v3/flexMetal/servers/{uuid}
      method: GET
    delete:
      path: /v3/flexMetal/servers/{uuid}
      method: DELETE
  ssh_key:
    create:
      path: /v3/sshKey
      method: POST
    read:
      path: /v3/sshKey/{uuid}
      method: GET
    delete:
      path: /v3/sshKey/{uuid}
      method: DELETE
  tag:
    create:
      path: /v3/flexMetal/tags
      method: POST
    read:
      path: /v3/flexMetal/tags/{tag}
      method: GET
    update:
      path: /v3/flexMetal/tags/{tag}
      method: PATCH
    delete:
      path: /v3/flexMetal/tags/{tag}
      method: DELETE
data_sources:
  tags:
    read:
      path: /v3/flexMetal/tags
      method: GET